// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package qq

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Food struct {
	FoodID        int32   `json:"food_id"`
	UserID        int64   `json:"user_id"`
	Name          string  `json:"name"`
	Kcal          float64 `json:"kcal"`
	Carb          float64 `json:"carb"`
	Fat           float64 `json:"fat"`
	Protein       float64 `json:"protein"`
	DefaultAmount int32   `json:"default_amount"`
}

type FoodPrice struct {
	UserID   pgtype.Int8 `json:"user_id"`
	FoodID   int32       `json:"food_id"`
	Price    int32       `json:"price"`
	Currency int32       `json:"currency"`
	Amount   int32       `json:"amount"`
}

type Meal struct {
	MealID  int32            `json:"meal_id"`
	UserID  int64            `json:"user_id"`
	Name    string           `json:"name"`
	Kcal    float64          `json:"kcal"`
	Carb    float64          `json:"carb"`
	Fat     float64          `json:"fat"`
	Protein float64          `json:"protein"`
	Amount  float64          `json:"amount"`
	Unix    pgtype.Timestamp `json:"unix"`
}

type MealFood struct {
	FoodID int32 `json:"food_id"`
	MealID int32 `json:"meal_id"`
	Amount int32 `json:"amount"`
}

type User struct {
	UserID int32  `json:"user_id"`
	Name   string `json:"name"`
}
